### ISSUE TITLE
Class table margin unexpectedly overlaps text below

### ISSUE THREAD

**Issue by Klorophane** [naturalcrit/homebrewery#295] opened 2017-01-19 15:41 UTC
When I try to render a class table that look mighty fine in editor's view:

1.  It gets all jigged up, and notice the white stripes on the edges. Image below.

Jigged up class table: http://imgur.com/lDpFmMQ

2. It suddenly overlaps with the text around it. Images below.

Before preview: http://imgur.com/eEjULtC
![image](https://user-images.githubusercontent.com/5878534/38678283-8f9eb57a-3e2e-11e8-8c6e-a7c949856b4f.png)

After preview:: http://imgur.com/YSw9rcE
![image](https://user-images.githubusercontent.com/5878534/38678262-82372aca-3e2e-11e8-9e6e-f9e1d55f019c.png)

The margins work fine in preview mode though. 

This changing margin also seems to occur at different times when the preview pane is updated, such as when adding text.

### Additional Details
I'm using Chrome and nothing of my knowledge is zoomed in or out. The issue persisted on two different computers. I've seen similar issues in the ''report issue'' thread.

**Share Link** : http://homebrewery.naturalcrit.com/share/r1bvNQ8CUe

**Comment by calculuschild** [comment] 2018-04-12 12:57
I've noticed that top and bottom margins of DIVS seem to be reset to 0 when zooming in and out. This might be related.

**Comment by sonaplayer** [comment] 2018-11-16 02:42
Was this solved?

**Comment by AlexeySachkov** [comment] 2018-11-16 07:35
Hi @sonaplayer, 

If I understand correctly, @calculuschild closed this issue because it may be caused by zooming. If you experiencing the same problem and not using zoom, could you please paste a `share` link to your brew here?

**Comment by sonaplayer** [comment] 2018-11-16 18:38
Sure. It happens on any brew I've made with a class table. It fixes itself if I change characters just below the table, but will unfix itself with time. I do not believe it shows up on everyone's browser so it may be hard to duplicate. I run Chrome (100% zoom) and Windows 10. Let me know if you need other info. 

http://homebrewery.naturalcrit.com/share/ByT72gGOG
It was failing for me when I loaded the page. Zooming in or out did not change the problem.

**Comment by AlexeySachkov** [comment] 2018-11-17 05:17
Wow, really interesting. I'm able to reproduce the issue, but I don't know what is exactly goes wrong and how to fix it.

So, to reproduce:
Copy code shared by @sonaplayer and remove all pages except first and second. It causes preview to be re-rendered and I see the following:
![image](https://user-images.githubusercontent.com/6417047/48657331-782fb880-ea40-11e8-9023-d6b11065fa10.png)

Editing the brew content after the table (for example updating the `Class Features` header leads to another one re-render and issue is gone.

I also noticed that by removing/adding empty lines just after the class table, `<p></p>` appears sometimes inside a `<div class='classTable wide'></div>` which causes change in the whole block height.

@calculuschild, could you please re-open this issue?

As I understand, it is not a critical bug (workaround exists), but it might be annoying

**Comment by calculuschild** [comment] 2018-11-17 05:36
Ah yes. A long while ago I narrowed it down to this minimal test case, but I never could figure out the solution: http://homebrewery.naturalcrit.com/share/BJiOViCntg

**Comment by sonaplayer** [comment] 2018-11-26 23:18
Not sure if this is helpful, but:

I noticed that when the over-run issue happens, the entire class table is shifted up slightly, and the text below it is shifted up even more, so that it overlaps. When you "refresh" the page by changing any characters below the table, it fixes everything by moving it all down, the text more than the class table, so it all looks right. 
Based on that, it seems like whatever shift is being applied shifts the objects lower on the page more than the objects higher on the page, as if the pixels are being shrunk. Perhaps it could have something to do with re-scaling the page to A4 dimensions? Does anyone notice this on normal dimension pages?

**Comment by calculuschild** [comment] 2018-12-03 17:11
Issue is described [HERE](https://old.reddit.com/r/homebrewery/comments/a1n2xm/issue_spacing_after_class_table/), text pasted for convenience:

> I am designing a class using the wonderful Homebrewery tool but every time I come back to the class I'm working on the text I have written after the Class Table has been bumped up to overlap with the bottom of the class table. If I add and then remove a pound symbol/hashtag from the title following the Class Table it adjusts itself, but I don't know if this will happen when I finish the class and decide to "publish" it. Is this something I have to worry about, or will it work properly when I publish?
>
>Here's an image so you know what I mean:
>
>https://i.redd.it/ct707ywq1d121.png

**Comment by calculuschild** [comment] 2021-01-10 01:53
Closing since I can no longer reproduce this; presuming Chrome has fixed the issue.

If this is still a problem, feel free to reopen the issue @Klorophane

**Closed by calculuschild** 2021-01-10 01:53 UTC
Labels: blocked, bug, complicated
