### ISSUE TITLE
[BUG] Share View on mobile - Text is pushed off columns; View on desktop is fine

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#816] opened 2018-12-03 12:00 UTC
Issue is described [HERE](https://old.reddit.com/r/homebrewery/comments/a2m3t3/text_problems_with_pok%C3%A9mon/), text pasted for convenience:

> [Issue] The text is misaligned on pages 1, 6 through 9, 16, and 18
>
> http://homebrewery.naturalcrit.com/share/SkZf7dgqf

Additional information provided:
> [Page 1](https://ibb.co/4RHzmxT)
> [Page 6](https://ibb.co/kHgfrzB)
>
> And yes, I am using Chrome

Checked "Related Issues", only found one, already closed.

**Comment by calculuschild** [comment] 2021-08-30 18:23
Duplicate of #625 . Closing

**Closed by calculuschild** 2021-08-30 18:23 UTC
Labels: duplicate
