### ISSUE TITLE
[BUG]Class Tables move up or down, only fixed by removing and re-adding characters before or after

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#814] opened 2018-11-30 11:46 UTC
Issue is described [HERE](https://old.reddit.com/r/homebrewery/comments/a1n2xm/issue_spacing_after_class_table/), text pasted for convenience:

> I am designing a class using the wonderful Homebrewery tool but every time I come back to the class I'm working on the text I have written after the Class Table has been bumped up to overlap with the bottom of the class table. If I add and then remove a pound symbol/hashtag from the title following the Class Table it adjusts itself, but I don't know if this will happen when I finish the class and decide to "publish" it. Is this something I have to worry about, or will it work properly when I publish?
>
>Here's an image so you know what I mean:
>
>https://i.redd.it/ct707ywq1d121.png

**Comment by AlexeySachkov** [comment] 2018-12-02 14:59
Duplicate of #295 

As I understand, it is an issue with live preview: Class Table sometimes renders incorrectly and it can be fixed even by editing text after the Class Table. I expect that this issue is not reproducible on `share` page

**Comment by calculuschild** [comment] 2018-12-03 17:09
Duplicate of #295.

**Closed** 2018-12-03 17:19 UTC
Labels: duplicate
