### ISSUE TITLE
Nearly entire page not working. 

### ISSUE THREAD

**Issue by werjak** [naturalcrit/homebrewery#277] opened 2017-01-03 01:40 UTC
Almost nothing works for me anymore. I used to go in and create stuff on my computer but I cant anymore. Where I should be able to type on either left or right side it is just blue. Almost none of the clickable buttons work. I tried going onto my laptop to see if maybe it was an issue with my dekstop but it works on neither. I have no idea how to possible fix the issue and I would really prefer not having to go back to google docs which sucks in comparison. The organization of the homebrewery- natural crit is extremely helpful.

**Comment by stolksdorf** [comment] 2017-01-03 03:46
You'll have to provide more details and screenshots of your issue.

**Comment by AlexeySachkov** [comment] 2020-12-18 08:31
@calculuschild, I think this issue can be closed as "cannot reproduce"

**Comment by calculuschild** [comment] 2020-12-18 08:33
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @werjak

**Closed by calculuschild** 2020-12-18 08:33 UTC
