### ISSUE TITLE
Multiple problems with text, print to pdf, flunks in conversions and rendering

### ISSUE THREAD

**Issue by Gigglebert** [naturalcrit/homebrewery#576] opened 2017-12-13 08:28 UTC
Computer: Toshiba with Core i3 
Web: Google Chrome

I have two huge problems for me since I'm no expert on making PDF's and the like so I'll list said problems:

1) The brews that I create are not stable, after leaving them for a while, the text shifts unpredictably (but mostly moves upwards) which seems to be a bug of some sort and I cant fix it. When I press enter in the middle of the text (and then delete the change), it goes back to normal which I also don't understand (I'll show an example later).

2) When I try to save as PDF, the preview looks fine but after I try to save it as PDF, this happens (The bottom part is completely white as if the page is smaller than it should be)

Before as a webpage: 
http://homebrewery.naturalcrit.com/print/r1QU9oWz1f?dialog=true

After as a PDF: 
file:///C:/Users/TOSHIBA/Downloads/The%20Homebrewery%20-%20NaturalCrit%20TEST.pdf

**Comment by Gazook89** [comment] 2021-01-04 18:27
This issue was opened 3 years ago, so just reviewing to see if it can be closed: I think it can be.  @calculuschild @ericscheid 

1. I haven't seen problems with shifting text myself in all the hours using it, and haven't seen it raised as an issue elsewhere (either here on github or the subreddit)...so perhaps it has been fixed in the meantime?  Would be impossible to know unless someone reports it again.

2. I suspect that the white space at the bottom of the page was due to a mismatch of the page size in Homebrewery and what the "save to pdf" prompt was set to for page size.  Likely one was set to Letter size, and the other to A4 page size.  This can be adjusted by the A4 snippet (or in the Save to PDF prompt).

Side note, the image formatting is really nice in this brew.

**Comment by calculuschild** [comment] 2021-01-04 20:58
Duplicate of #295

As for 1, it looks like a duplicate of #295, which I'm not sure ever got solved. We can close this as a duplicate though. I think you are right about 2.

@Gigglebert, if you are still having this issue, take a look at #295 and see if that matches your situation. Otherwise feel free to reopen this issue.

**Closed by calculuschild** 2021-01-04 20:58 UTC

**Comment by calculuschild** [comment] 2021-01-04 21:01
Duplicate of #295
