### ISSUE TITLE
Applying a filter to background images results in the image being very blurry and pixelated in exported PDFs.

### ISSUE THREAD

**Issue by CristiIonut** [naturalcrit/homebrewery#487] opened 2017-09-08 23:28 UTC
### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<img 
  src='http://i.imgur.com/DOi8aq2.png' 
  style='position:absolute;
  top:100px;
  left:-50px;
  height:540px;
  filter:grayscale(30%);' />

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-21 23:44
Are you still having this issue? Could you please provide a screenshot and the *share* link to your document so we can see what the problem is?

**Comment by AlexeySachkov** [comment] 2020-12-25 12:05
@calculuschild, @ericscheid, I suggest that we close this one

**Comment by calculuschild** [comment] 2020-12-25 19:59
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @CristiIonut

**Closed by calculuschild** 2020-12-25 19:59 UTC
Labels: needs more info
