### ISSUE TITLE
A4 PDFs leave white gap around bottom and right edges

### ISSUE THREAD

**Issue by jimcullenaus** [naturalcrit/homebrewery#468] opened 2017-08-16 12:57 UTC
I set the following at the top of the document

```
<style>
.phb {
    width : 210mm;
    height : 297mm;
}
</style>
```

And by default, Chrome wanted to print it out at a 98% scale, which left large white borders around it.

When set to 100% scale manually, there is a very small white bar at the *top* of each page, but it goes fully to the bottom and right. However, the very bottom of what *should* appear on each page is instead bled on to the next page, with nearly an entire blank page below that. So on 100% scale, you have odd pages with a small white strip at the top and content for the rest of the page; on odd pages you have a small white strip at the top, a small strip of stuff below that (what should be the bottom of the previous page), and then the rest of the page is blank.

Compare [this PDF, at 99% scale](https://drive.google.com/open?id=0ByJHrWzI6zNOQm9SMVFxUVFsdEE), with [this PDF, at 100% scale](https://drive.google.com/open?id=0ByJHrWzI6zNOalEybTNYb3p5R0U). Both generated from [this Homebrewery document](http://homebrewery.naturalcrit.com/share/VydFOpkag).

This problem exists both when printing to PDF using Chrome's PDF printer, and when using the macOS built-in PDF printer.

This is essentially a duplicate of #461, which was closed by the user who lodged it without a solution.

**Comment by Zephilinox** [comment] 2017-08-18 04:37
There wasn't really a solution to my issue, it just resolved itself. One thing I did that helped at the time was change 297mm to 296.9, or maybe it was 210mm to 209.9. Basically just adjust the values slightly until there's no more white border.

**Comment by jimcullenaus** [comment] 2017-08-18 16:03
New information: this seems to be a Mac-specific problem. I haven't had the chance to check Linux yet, but on Windows the problem does **not** exist.

**Comment by Theusfilipe** [comment] 2017-12-22 23:31
It does exist I use windows and I had that problem.

This is how I want it to look like, as it appears on the viewer.


![image](https://user-images.githubusercontent.com/3932016/34314642-c791150a-e75c-11e7-9f7f-dfe3890a7b77.png)

and this is how it appears on the pdf:

![image](https://user-images.githubusercontent.com/3932016/34314662-14c79eac-e75d-11e7-86b3-dcdbfbe8a37f.png)

I was going to post on another post but I found this one.

**Comment by calculuschild** [comment] 2017-12-23 02:00
Your print paper size is A4 but your homebrew is Letter size.

**Comment by jimcullenaus** [comment] 2018-01-03 11:36
@calculuschild I assume that comment was in reply to @Theusfilipe? Because for my initial ticket that was definitely *not* the case.

**Comment by calculuschild** [comment] 2018-01-03 15:37
@jimcullenaus Correct. I was responding to @Theusfilipe.

**Comment by calculuschild** [comment] 2018-04-17 12:30
@jimcullenaus Is this still an issue? It's been a while, but I'm curious if this was a temporary Chrome bug or if you still notice it.

**Comment by jimcullenaus** [comment] 2018-04-18 09:58
Yes, I can confirm that it is still an issue. [Here's a zoomed-in screenshot of the corner of a page](https://i.imgur.com/VpEwU2k.png) when printing at 100% onto A4 paper with the A4 page size in CSS.

**Comment by Gazook89** [comment] 2021-09-10 21:47
I do not have this problem in 2021, using macOS and Chrome. Used the A4 snippet and set page size to A4:  no extra whitespace on any side.  Not sure what changed (but the snippet is now using height: 296.8mm).  

Going to close this since I haven't seen this issue come up on the subreddit in at least a year and I can't reproduce it.  If it is still an issue this can definitely be re-opened.

**Closed by Gazook89** 2021-09-10 21:47 UTC
Labels: needs more info

**Comment by davideghz** [comment] 2022-11-28 19:56
use
```
.page {
    width : 210mm;
    height : 296.8mm;
}
```
