### ISSUE TITLE
"Tables" menu not visible on /new/ page load.

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1783] opened 2021-10-31 20:58 UTC
When I go to create a new brew, the "tables" snippet menu is not visible in the snippet toolbar.  This only happens when the renderer is set to v3.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/58999374/139600956-16aaede4-f0df-40b3-9062-ab004c586ed5.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/58999374/139601005-463baebd-1057-4c8c-9c65-65b0881a3004.png">

If I switch to Style editor, and then back to Content editor, it appears.

**Comment by calculuschild** [comment] 2021-10-31 21:03
I can confirm this. Very interesting observation.

**Comment by AlexeySachkov** [comment] 2022-01-12 20:15
I can't reproduce this anymore, seems to be fixed by some change?

![image](https://user-images.githubusercontent.com/6417047/149214942-e9f43851-e44b-4934-a4ec-1b168fa3f64d.png)

**Comment by calculuschild** [comment] 2022-01-12 20:18
I agree. There was probably an early bug forgetting to give `/new` proper access to the V3 snippets, but clearly this isn't an issue anymore.

**Closed by calculuschild** 2022-01-12 20:18 UTC
Labels: P1 - high priority
