### ISSUE TITLE
"ā,ē,ī,ō,ū" not capitalised in #^n titles

### ISSUE THREAD

**Issue by Dustfinger1** [naturalcrit/homebrewery#355] opened 2017-03-06 01:24 UTC
### Additional Details

"ā,ē,ī,ō,ū" don't capitalise when I use "#" titles. Other characters with special accents (ö,æ,î,è) work just fine it seems, but these guys are weird. Seems to be the case no matter how many "#"s are used. Maybe they're exempted from the capitalisation for some reason?

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# ### Cān't gēt īt wōrking, dūde. 
# ## ThĪs dŌĒs't work either.
</pre></code></details>

**Comment by calculuschild** [comment] 2017-03-07 15:17
I am wondering if these fonts simply didn't have those characters included, so it's reverting to another font to draw those. Is [this](https://www.reddit.com/r/UnearthedArcana/comments/3vpphx/5e_font_package_embeddable_cc_edition/) where the fonts came from? In that case maybe the creator on Reddit can make an update to the font.

**Comment by calculuschild** [comment] 2020-10-26 20:50
Closing as duplicate of #116

**Closed by calculuschild** 2020-10-26 20:50 UTC
Labels: bug, phb-style
