### ISSUE TITLE
+Unable to See Full Screen

### ISSUE THREAD

**Issue by bishop6185** [naturalcrit/homebrewery#433] opened 2017-07-02 20:31 UTC
Hi my screen doesn't show everything when I try to save to pdf or even view any sort of homebrewery file?

![screenshot 2017-07-02 13 28 51](https://user-images.githubusercontent.com/27327092/27773248-7eb4f91a-5f2a-11e7-992c-4f12e3e43842.png)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Pendragon888oo** [comment] 2017-08-01 20:44
http://homebrewery.naturalcrit.com/edit/SJfj9xT48b

**Comment by AlexeySachkov** [comment] 2021-01-24 12:23
@naturalcrit/issue-managers, I suggest that we close this issue as an outdated one

**Comment by Gazook89** [comment] 2021-08-21 01:31
Closing due to age and not much information to reproduce.  On Pendragon888oo's brew, it appears there is any issue with text flowing off page which can be fixed by `\page`, which it looks like has also been utilized so I'm assuming it's not an issue any more.  It can be reopened if needed.

**Closed by Gazook89** 2021-08-21 01:31 UTC
