### ISSUE TITLE
Help! Cannot "get PDF" on a large document I have created

### ISSUE THREAD

**Issue by Kanaellars** [naturalcrit/homebrewery#201] opened 2016-09-17 23:20 UTC
---

**Browser Type/Version**: Google Chrome (most recent update)

**Issue Description**: Cannot get PDF of brew. I have created quite a sizeable brew for a home brew camp (about 140 pages), and have now gone to get a pdf of the final project, only to get time-outs, failures, and page not responding errors at all attempts.

Can someone please advise why I cannot seem to get a final copy of this brew?

![image](https://cloud.githubusercontent.com/assets/22265690/18611569/1d8f10d0-7d35-11e6-86c0-d6d4c0fb6002.png)

**Comment by stolksdorf** [comment] 2016-09-17 23:28
The simple answer is that rendering a brew that large takes up too much memory and crashes Chrome. It doesn't crash while editing it, because I have written special code that only renders the page you are currently looking at. 

You could try and reduce the filesize of the images, but I doubt that would be enough. I suggest just splitting it out into smaller brews, like by chapter. 

I did not design the site to handle people writing entire books in it, haha. Hopefully that helps.

**Comment by Kanaellars** [comment] 2016-09-18 07:33
Is there any way around this? I mean, I suppose I could break it all up, but that will reset my page numbering for each chunk, meaning I would have to go back and manually assign all of the page numbers as well. 

Is there any way in increase chromes available memory?

**Comment by pbexxx** [comment] 2016-09-24 04:30
I'm having a similar issue where it renders fine,  however it's only the first 3 pages (of the original 35 pages)... ill try the slitting up but the page numbering would be an issue for me too

**Comment by stolksdorf** [comment] 2016-09-24 14:50
@Kanaellars this is getting out of the scope of what I can help you with. However if you issue with breaking up your brew is page numbers is page numbers, look into using [CSS counter resets](https://developer.mozilla.org/en/docs/Web/CSS/counter-reset)

@pbexxx You are having a completely different problem. If it's rendering only a subset of your pages, this is most likely because you have formatted your HTML poorly. This is becoming the most common issue I'm getting. I have an experiemntal HTML checker on my staging version of the site [here](http://homebrewery-staging.herokuapp.com/new). copy and paste your brew there and see if any errors pop up.

**Comment by AlbertMokrejs** [comment] 2016-10-12 15:31
What would the variable name for the CSS counter reset be?

**Comment by vorpalhex** [comment] 2016-10-16 05:13
@Kanaellars You may want to try using a tool like https://www.npmjs.com/package/markdown-pdf along with the Homebrewery CSS to be able to build such a large PDF. This is ultimately *not* a bug as far as Chrome is concerned since a given page should never be able to use over an upper bound of memory.

**Comment by Dkamanus** [comment] 2016-10-25 01:34
@stolksdorf Excellent. 

THAT tools should be on the initial homebrew page. I was heavy the same problem rendering a 7 page homebrew and couldn't render 3 pages. That tool alone will help me with the formatting on my brew.

Thanks a lot. Liked the tool so much I might send some money your way.

Do more :D

**Comment by Gazook89** [comment] 2021-01-03 20:06
@calculuschild  This issue can likely can be closed.

**Comment by calculuschild** [comment] 2021-01-08 21:34
I'm going to leave this open, since the issue is with generating the PDF of large brews, not just viewing them in the editor. I would like to verify with a large (140+ page) brew that it does not crash the browser when generating the PDF.

**Comment by calculuschild** [comment] 2021-04-07 03:36
Alright, I don't see any crashes happening, however I do see that even blank documents with just the background image become tremendously large because the image data for the parchment background is duplicated in each page; this, plus other images, might overload somebody's RAM? But I think this is an issue that deserves its own discussion. Going to close this and open a new issue to address that issue specifically.

**Closed by calculuschild** 2021-04-07 03:36 UTC
