### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Mlynch1** [naturalcrit/homebrewery#764] opened 2018-10-01 18:46 UTC
Whenever I click on my username in the top right it will send me to the intro screen.

**Comment by RKuerten** [comment] 2018-12-14 23:33
Is your username an e-mail? 
If it is, that's a known bug. See issue #807.

**Comment by ericscheid** [comment] 2020-11-14 16:47
Closing as duplicate of #807 (which is collecting all cases of this)

**Closed by ericscheid** 2020-11-14 16:47 UTC
Labels: bug, duplicate
