### ISSUE TITLE
Printing Margins Help!

### ISSUE THREAD

**Issue by 1sttimecaller** [naturalcrit/homebrewery#524] opened 2017-10-19 17:00 UTC
Hey all,

I am using chrome and trying to print my homebrew DM screen. However, every time I do, I get white margins around the pdf. 

I have tried playing with all the different margin settings for my printer, while saving the pdf in chrome, and tried printing from both chrome and adobe with 0 margins set. 

No matter what, I get white space (although how much definitely varies).

**Share Link** : http://homebrewery.naturalcrit.com/share/HJQQbqx3hb

**Comment by calculuschild** [comment] 2017-10-19 17:18
Do you have your page size set correctly? If the document is a different
page than your pdf print settings you will get white borders.

**Comment by 1sttimecaller** [comment] 2017-10-19 17:23
It should just be standard letter size if I'm not mistaken? I combed through the file for any A4 size settings and didn't see any. Also if I set it to A4 the page shifts...so I am going to guess that I have everything set right in homebrewery. This is my first brew though, so I could be wrong.

**Comment by calculuschild** [comment] 2017-10-19 17:48
I just tried printing it myself with standard letter size, default margins, and it seems totally fine to me. Can you maybe show a screenshot of what you're getting?

**Comment by 1sttimecaller** [comment] 2017-10-19 18:06
<img width="276" alt="screen shot 2017-10-19 at 2 06 04 pm" src="https://user-images.githubusercontent.com/32937680/31786491-ae25d636-b4d6-11e7-9218-6054ebaca191.png">

**Comment by calculuschild** [comment] 2017-10-19 18:08
Wait wait... So does your pdf file have these margins or is it only in the
paper copy?

**Comment by 1sttimecaller** [comment] 2017-10-19 19:04
Only when I print. That one was done exactly how you said you set your print up. 

No matter what settings I use printer wise, space is always there. Actually, this is the best it gets...Other settings make it really small

**Comment by calculuschild** [comment] 2017-10-19 19:32
Ok ok. So if your PDF is being generated correctly without whitespace, then
the Homebewery site has done its job. Once you start printing on paper,
that starts to be more an issue with your printer than anything to do with
the website.

Some printers are simply designed to not print all the way to the edge so
they don't spill ink all over the inside od the printer. In fact it looks
to me like your printed page doesn't have a margin around the page, but
rather has cut off the outside 1/4 inch or so. Its *trying* to print all
the way to the edge, but when it gets to the printer it just isn't
programmed to do that. Options then would be to just print as big as you
can and trim off the white edge, or take your file to a copyshop where they
have special full-page printers and can make it look nice and shiny for a
couple bucks.

**Comment by 1sttimecaller** [comment] 2017-10-19 19:46
I work at a place where we often print to the edge of a page. We make a lot of full-page ads, and when I print those as pdfs I have no issue. 

Obviously, I cannot show you an example of that.

**Comment by calculuschild** [comment] 2021-01-08 21:48
Closing since we have made many related improvements since this was posted, and the issue is likely solved.

If you are still experiencing this issue, feel free to reopen and provide information, @1sttimecaller

**Closed by calculuschild** 2021-01-08 21:48 UTC
