### ISSUE TITLE
Can't access my saved brews

### ISSUE THREAD

**Issue by Fishgutsconquersall** [naturalcrit/homebrewery#662] opened 2018-04-17 01:57 UTC
Clicking on my name in the top right corner does nothing but bring me to the same welcome example page thing with all the instructions on it.

**Comment by calculuschild** [comment] 2018-04-17 12:06
Can you right-click your username and select "copy link address", then paste it, what do you get?

Also, when you last logged in, did you put your username as an email address or just a name? I remember that was an issue people were having a while back where it would still log you in, but your profile was broken.

**Comment by pookaskreations** [comment] 2018-09-18 01:13
I'm having the same problem. I can't access my brews and aren't given a url link to my saved brews. The copied link sends me to the same start page.

**Comment by calculuschild** [comment] 2018-09-18 11:30
I would ask the same of you: Can you right-click your username and select "copy link address", then paste it here?

**Comment by calculuschild** [comment] 2020-10-25 02:54
Closing. Likely duplicate of #807

**Closed by calculuschild** 2020-10-25 02:54 UTC
