### ISSUE TITLE
[Request] QR code on paper

### ISSUE THREAD

**Issue by bakgaard** [naturalcrit/homebrewery#538] opened 2017-10-31 19:43 UTC
It sounds odd, but if I have a brew printed out, and a new version comes out, I would like to quickly be able to get the new version.

Is it hard?
Most likely not, cause you can get them as follow:
``https://api.qrserver.com/v1/create-qr-code/?data=[URL-encoded-text]&size=[pixels]x[pixels]``

Example:

``http://api.qrserver.com/v1/create-qr-code/?data=http://homebrewery.naturalcrit.com/&size=100x100``

Actual use:

```
<img 
    src='https://api.qrserver.com/v1/create-qr-code/?data=http://homebrewery.naturalcrit.com/&amp;size=100x100'
    style='width:100px;mix-blend-mode:multiply'/>
```

The trick is, that it should be the ``Shared`` version which is in the link.

**Comment by ericscheid** [comment] 2020-11-14 07:31
Added to Epic #1096

**Comment by ericscheid** [comment] 2020-11-14 07:37
Duplicate of #539

**Closed by ericscheid** 2020-11-14 07:37 UTC
Labels: duplicate
