### ISSUE TITLE
Feature suggestion: Collapse all + Code Filters

### ISSUE THREAD

**Issue by Zarhog** [naturalcrit/homebrewery#1932] opened 2021-12-29 17:16 UTC
## Description

Would it be possible to add a collapse all option for the code, this would make the code easier to navigate as well as faster to find the appropriate page. in addition if there was a way to filter it so that only the code on a specific page or range of pages will show that would be of great value to those of us that find it hard to comb though code multiple times to find the correct page code.

an additional feature request would be a short cut option where you CTR + Left Click on the page on the right and it jumps to the code for that page on the left.

You can imagen the benefits from this feature being added as it would allow for quick and easy manipulation of a specific page, redacting the time spent on a specific part of code

**Comment by calculuschild** [comment] 2021-12-29 19:02
You can collapse pages by clicking the arrow icon below each `\page` in your document. You can collapse/expand all with `CTRL + [` and `CTRL + ]`, although we will include actual clickable buttons later. Simply collapse all, and then expand the individual page(s) you want to look at.

As for code jumping/sync this is already mentioned in #1756, and we'll eventually add that feature.

I will close this issue as a duplicate of #1756 since the other suggestion (code folding) is already implemented.

Feel free to supply more info if there is something else we're missing and you want to clarify.

**Closed by calculuschild** 2021-12-29 19:02 UTC
