### ISSUE TITLE
Double Pages

### ISSUE THREAD

**Issue by Marcobertini6** [naturalcrit/homebrewery#862] opened 2020-01-07 15:59 UTC
Hi,
when I go to make "PDF" the fyle goes out with double pages (12 instead 6, for example) and these 6 more are white pages. In which way can I solve this problem?
Thanks

**Comment by AlexeySachkov** [comment] 2020-01-08 08:08
@Marcobertini6, please put a `share` link to your brew here, so we can reproduce the issue and track down the problem

**Comment by Marcobertini6** [comment] 2020-01-08 11:24
https://homebrewery.naturalcrit.com/edit/HJlhC3kzSm

**Comment by Marcobertini6** [comment] 2020-01-11 11:38
Some news?

**Comment by ericscheid** [comment] 2020-01-12 07:34
Your brew is 2 pages, which leads me to suspect the two extra blank pages are an overflow issue. I bet if you were to insert a `\page` break anywhere you would now have *three* extra blank pages.

What size paper are you printing on? Since the text appears to be Italian, I'm guessing you're in the EU, and thus likely to be printing to A4? Try inserting the CSS for A4 page size, which looks like this:

````
<style>
  .phb {
    width : 210mm;
    height : 296.8mm;
  }
</style>
````

**Comment by Marcobertini6** [comment] 2020-01-12 11:15
> What size paper are you printing on? Since the text appears to be Italian, I'm guessing you're in the EU, and thus likely to be printing to A4? Try inserting the CSS for A4 page size, which looks like this:

Yes, I'm in EU! Unfortunately I have already put that formula but for now it has not solved the problem

**Comment by AlexeySachkov** [comment] 2020-01-14 13:56
@Marcobertini6, please try [this version](https://homebrewery.naturalcrit.com/share/rkXRoDrieU)

The main difference is that I've replaced `<div style='margin-top:0px'></div>`  with `<br />` - these empty div's seems to confuse Chrome printing engine

**Comment by Marcobertini6** [comment] 2020-01-14 21:59
Okay, fixed. It seems to me that the problem was the length of the margins, too long!
Thanks

**Comment by calculuschild** [comment] 2020-02-06 15:40
Closing because this appears to be solved.

**Closed by calculuschild** 2020-02-06 15:40 UTC
