### ISSUE TITLE
Bullets, Dashes, and Asterisks...

### ISSUE THREAD

**Issue by EpicSauce8** [naturalcrit/homebrewery#672] opened 2018-04-25 06:32 UTC
So I was playing around with Markdown and HomeBrewery and this happened:

![image](https://user-images.githubusercontent.com/16732781/39226445-7103bf10-4807-11e8-9c83-920e46750900.png)

Now with the problem code...
First bug: (in code)
Removing line 26 resolves the issue. As does adding something to it (continues the previous bullet though and not a new line, may be expected behavior).

Second bug: if I remove the separating line(34) or add something to it, then it all becomes proper hanging indent again until the bugbear line. Same happens if you change 35-37 to dashes instead of asterisks. I have tested all issues in Edge, some in Chrome.

<details><summary>Code for copy/pasta: (had to add grave accents to the blank lines so the code would show instead of formatting due to spacing which will show differently when plugged into Homebrew)</summary><code><pre>
- I guess this is bullet form.
- And continuing with the bullets.
`
* I wonder if this causes the same bug as below?
* Does not seem to be the case.
That's a whole new timorous beasty.
___
- Can this be close groups of one line text? It is!
- And all without the indent. I wonder what happens if I cross into the next line.
- So really this is a hanging indent toggle. That's useful. Kinda. Now I really want to put in a lot of jibberish and filler text to see if the hanging applies to the first line, like it should. Wonderful.
`
* This does more bullets.
* They look the same but I will probably get them confused with the italics.
* Playing with the bug some more.
`
***I may have found a bug. Bugbear? Bugbear.***
</pre></code></details>

**Comment by misthero** [comment] 2018-04-26 09:16
I think you can add another linebrak to separate lists instead of using the grave accent, like this


```
- I guess this is bullet form.
- And continuing with the bullets.


* I wonder if this causes the same bug as below?
* Does not seem to be the case.
```

**Comment by ericscheid** [comment] 2020-11-13 05:16
There is a special css rule in the phb.css for an `ul` following a `hr`, it looks like this: 

```
.phb hr+ul {
    margin-bottom: .5em;
    padding-left: 1em;
    text-indent: -1em;
    list-style-type: none;
```

This rule was set up to do the special formatting of abilities etc inside monster blocks.

If you want to separate two groups of list items into two lists, then put two blank lines between.

Kinda working as intended, if perhaps too broadly. Closing.

**Closed by ericscheid** 2020-11-13 05:16 UTC
Labels: phb-style
