### ISSUE TITLE
h1 header makes Split Table columns unaligned if said table is near the end of the page

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#844] opened 2019-03-21 10:19 UTC
This is a strange one, see [THIS](https://old.reddit.com/r/homebrewery/comments/b0a1vp/cant_figure_this_out_please_help/) reddit thread for a detailed explanation of what happened.

**Comment by ericscheid** [comment] 2019-03-21 15:13
My full analysis is on reddit, but the base cause for this is that the triple-backtick markup renders as `<p><code></code></p>` into html, and then there is CSS for `code` that applies `visibility:hidden` and  `-webkit-column-break-after: always;`. 

That CSS for `<code/>` is fine.

The problem is that it is wrapped in a `<p/>`, and there's a CSS rule for that that sets `padding-bottom : 0.8em` ... and thus padding-space gets inserted after the column-breaking element, and hence preceding the following content i.e. the table.

----

In this particular case, the easy fix is to delete the column-breaking markup (i.e. the double-triple-backticks) ... then the author has specified two equal height blocks of break-avoid content inside a `<div style='column-count:2'>` ... and the browser will auto-insert a break itself, and there's no other content between that will have errant padding screwing things up.

**Comment by ericscheid** [comment] 2019-03-21 15:17
How to fix this though for the general case?

There is no easy CSS fix.

Maybe change the html that gets emitted for the column-break markdown .. change it to emit `<div class="column-break"></div>` and have a CSS rule for that.

Might not be that easy though - the `<p>..</p>` might be getting emitted separately from the `<code></code>`. So maybe a post-render cleanup step?

**Comment by chrisbrickhouse** [comment] 2019-03-21 18:40
I think a post-render cleanup step would be easiest to maintain. We currently use [markedjs](https://github.com/markedjs/marked) to render the markdown rather than code we maintain which means we'd need to include a custom fork of that package just for this issue which seems excessive.

**Comment by ericscheid** [comment] 2020-11-11 16:18
Would be fixed in #1093 which is an overhaul of the rendering, including using `\column` instead of code-fences for signalling a column break (theoretically emitting a render of `<div class="column-break"></div>`

Of course, none of that is really necessary, since the explicit column break isn't really needed.

Adding `Tweak` label so someone could submit a PR that deletes the code-fence https://github.com/naturalcrit/homebrewery/blob/master/client/homebrew/editor/snippetbar/snippets/snippets.js

**Comment by calculuschild** [comment] 2021-09-14 17:12
The main issue had been solved some while back (can't remember where), but even with backticks this doesn't seem to be a problem anymore no Legacy.

#1681 Removes the backticks from the Legacy snippet anyway, so this is now fully solved.

**Closed by calculuschild** 2021-09-14 17:12 UTC
Labels: blocked, tweak
