### ISSUE TITLE
Creating PDF with Adobe PDF printer breaks class table border.

### ISSUE THREAD

**Issue by drunkenvalley** [naturalcrit/homebrewery#608] opened 2018-01-24 12:58 UTC
I am using Chrome when trying to print. I am working on a homebrewery [here](http://homebrewery.naturalcrit.com/share/rkhaNdMMM). I chose to get a PDF version, which prompts the print dialog. 

The preview looks fine, but when I print as Adobe PDF the end result is this:

![image](https://user-images.githubusercontent.com/1728144/35333191-21cfca28-010e-11e8-9624-b012da67208f.png)

I can reliably reproduce this effect via the following:
1. Open my [homebrew](http://homebrewery.naturalcrit.com/share/rkhaNdMMM) in Chrome.
2. Select "Get PDF", which will bring up the print menu.
3. Select "Adobe PDF" as my destination.
4. Print and wait for Adobe Acrobat Pro DC to finish compiling.

After discovering this, I opted to use "Save as PDF" as the destination. This renders fine.

**Comment by GorchD20** [comment] 2018-04-19 04:38
Mind looks fine, but when I use Save as PDF, it does something like this (but the entire thing is border-corners the whole way around)
![class table error](https://user-images.githubusercontent.com/33652551/38971610-ced60230-4350-11e8-9465-a86026fbaab3.png)

**Comment by Gazook89** [comment] 2021-09-12 04:15
This issue is 3 years old and I'm just trying to close some stuff up--- unfortunately, I do not have Adobe Acrobat to give this another test run to try and reproduce.  @drunkenvalley / @GorchD20  I know this is old, but any chance you want to give it another shot and let us know if you can reproduce?  

Since it works fine with Chrome's pdf printer (and FF), I'm not sure there is much we could do to accommodate Adobe anyway.  Going to close this for now but it can be re-opened if necessary.

**Closed by Gazook89** 2021-09-12 04:15 UTC

**Comment by calculuschild** [comment] 2021-09-12 04:22
I have Acrobat and just tried it. Looks fine to me (although I have the latest version of Adobe Cloud, so old ones could very well be broken.) In any case you are right, this is a bug with Acrobat; not something we can fix here.

![image](https://user-images.githubusercontent.com/5878534/132972080-0ef62415-f724-4813-8f09-2c711d696245.png)
