### ISSUE TITLE
Partial Page Renderer Issue

### ISSUE THREAD

**Issue by Tsurumah** [naturalcrit/homebrewery#273] opened 2016-12-28 01:40 UTC
Not sure if working as intended, but the Partial Page Renderer renders, literally, a partial page. If you scroll down, you can only see--at least, on my few computers--1/2 to 3/4 of the page, generally cutting off the bottom quarter to half. 

Could also be on my end, too, I suppose.

Is there a way to disable the Partial Page Renderer client side, or increase the number of pages that are rendered, around the visible page, client side, of course. First 20-some-odd pages renders fine, however, with no issues, and everything else comes up fine--just makes it difficult to judge distances on images and such.

**Comment by IrdunWindseeker** [comment] 2017-03-02 08:58
Hi, I am having the same problem. I have roughly a 98-page homebrew that I would like to share with other people via the share link, but the rendering makes it so that on certain pages as soon as you scroll down the entire page is gone, replaced by a scroll wheel. How can I fix this so that I can share my brew with people?

**Comment by calculuschild** [comment] 2021-01-09 00:10
Closing since we have made many related improvements since this was posted, and we can no longer reproduce the issue.

If you are still experiencing this issue, feel free to reopen and provide information, @Tsurumah

**Closed by calculuschild** 2021-01-09 00:10 UTC
