### ISSUE TITLE
Sticky divider when showing Brew Properties.

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1486] opened 2021-07-30 13:37 UTC
When the _Brew Properties_ editor mode is selected, dragging the editing:preview pane divider does not release when the mouse is released. One must hit reload to release.

This does not happen with _Brew Editor_ or _Style Editor_ modes.

**Comment by calculuschild** [comment] 2021-07-30 13:41
Duplicate of #1388.

**Closed** 2021-07-30 13:42 UTC
Labels: UI/UX, bug, bug-regression
