### ISSUE TITLE
Improve spacing with text before class tables

### ISSUE THREAD

**Issue by 8139467t8935yhtg8924** [naturalcrit/homebrewery#126] opened 2016-06-06 03:33 UTC
**Browser Type/Version**: vanilla whatever the newest chrome is, i clean installed because some of my plugins were messing it up.

**Operating System**: OSX 10.10.4

**Issue Description**: imgur.com/o5ycv34, also when i go to print its not displaying the background in the pdf it generates.

**Brew code to reproduce**:

```

# Strong Ranger

##### The Ranger
___
| Level | Proficiency Bonus | Features | Tricks | Spells Known | 1st | 2nd | 3rd | 4th | 5th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Hunter's Strike, Natural Explorer, Animal Companion | 4 | — | — | — | — | — | — |
| 2nd | +2 | Spellcasting, Combat Style | 4 | 2 | 2 | — | — | — | — |
| 3rd | +2 | Primeval Awareness, Vanish | 5 | 3 | 3 | — | — | — | — |
| 4th | +2 | Ability Score Improvement | 5| 3 | 3 | — | — | — | — |
| 5th | +3 | Extra Attack | 5 | 4 | 4 | 2 | — | — | — |
| 6th | +3 | Natural Explorerer improvement, Hunter's Prey | 6 | 4 | 4 | 2 | — | — | — |
| 7th | +3 | Land's Stride | 6 | 5 | 4 | 3 | — | — | — |
| 8th | +3 | Ability Score Improvement | 6 | 5 | 4 | 3 | — | — | — |
| 9th | +4 | Defensive Tactics | 7 | 6 | 4 | 3 | 2 | — | — |
| 10th | +4 | Natural Explorer improvement |7 | 6 | 4 | 3 | 2 | — | — |
| 11th | +4 | Combat Style Feature | 7 | 7 | 4 | 3 | 3 | — | — |
| 12th | +4 | Ability Score Improvement | 8 | 7 | 4 | 3 | 3 | — | — |
| 13th | +5 | — | 8 | 8 | 4 | 3 | 3 | 1 | — |
| 14th | +5 | Hide in Plain Sight | 8 | 8 | 4 | 3 | 3 | 1 | — |
| 15th | +5 | — | 9 | 9 | 4 | 3 | 3 | 2 | — |
| 16th | +5 | Ability Score Improvement | 9 | 9 | 4 | 3 | 3 | 2 | — |
| 17th | +6 | — | 9 | 10 | 4 | 3 | 3 | 3 | 1 |
| 18th | +6 | Feral Senses | 10 | 10 | 4 | 3 | 3 | 3 | 1 |
| 19th | +6 | Ability Score Improvement | 10 | 11 | 4 | 3 | 3 | 3 | 2 |
| 20th | +6 | Foe Slayer | 10| 11 | 4 | 3 | 3 | 3 | 2 |


## Class Features

As a ranger, you gain the following class features.
```

**Related Images** :

**Comment by 8139467t8935yhtg8924** [comment] 2016-06-06 03:35
also i want to say this is awesome, you're amazing, and thanks for making this. seriously man, you rule.

**Comment by 8139467t8935yhtg8924** [comment] 2016-06-07 02:09
Ah okay I figured out that it was my fault the background wasn't loading on images. For whatever reason my settings had background images turned off. So case closed on that one. Still don't know about the table text though.

**Comment by stolksdorf** [comment] 2016-09-13 15:20
The way that full class tables work with surrounding text has always been a difficult/tricky thing. I'll falg this to take a look at later.

Reminder for me: Try moving the top margin onto the h5 header when you detect it's being used in conjunction with a table.

**Comment by calculuschild** [comment] 2021-01-08 21:49
Closing since we have made many related improvements since this was posted, and we can no longer reproduce the issue.

If you are still experiencing this issue, feel free to reopen and provide information, @8139467t8935yhtg8924

**Closed by calculuschild** 2021-01-08 21:49 UTC
Labels: feature, phb-style
