### ISSUE TITLE
Empty column 1 collapses, column 2 gets shifty

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1566] opened 2021-08-13 01:40 UTC
This only happens with the v3 renderer, not the legacy renderer (using legacy column breakers).

```
# Column calumny

\column

## column two??

Sed enim risus, congue non, tristique in, commodo eu, metus. Aenean tortor mi, imperdiet id, gravida eu, posuere eu, felis. Mauris sollicitudin, turpis in hendrerit sodales, lectus ipsum pellentesque ligula, sit amet scelerisque urna nibh ut arcu. Aliquam in lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla placerat aliquam wisi. Mauris viverra odio. Quisque fermentum pulvinar odio. Proin posuere est vitae ligula. Etiam euismod. Cras a eros.

:

Nulla facilisi. In vel sem. Morbi id urna in diam dignissim feugiat. Proin molestie tortor eu velit. Aliquam erat volutpat. Nullam ultrices, diam tempus vulputate egestas, eros pede varius leo, sed imperdiet lectus est ornare odio. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin consectetuer velit in dui. Phasellus wisi purus, interdum vitae, rutrum accumsan, viverra in, velit. 
```

![image](https://user-images.githubusercontent.com/2605467/129292409-25816f11-d754-40b6-9d93-a00305227322.png)

**Comment by Gazook89** [comment] 2021-08-13 01:51
This doesn't fix the actual issue, but a quick workaround is:

```
# Column Calamity
:

\column

Here is some text in the second column.
```

**Comment by AlexeySachkov** [comment] 2021-12-30 19:28
Observation 1: a block with zero height doesn't trigger a column break. `legacy` renderer/syntax inserts a `<pre><code></code></pre>` elements, which take almost `12px`:

![image](https://user-images.githubusercontent.com/6417047/147781823-16a5ae4d-dde9-49ad-a5b9-002baea0ebfd.png)

If I set height of `.columnSplit` (which is zero by default) to at least `1px`, it starts to work, but in an unexpected way:

![image](https://user-images.githubusercontent.com/6417047/147781887-f96ad99c-344a-4d35-8772-743910b4e1d4.png)

If I further disable `break-before` it works as expected:
![image](https://user-images.githubusercontent.com/6417047/147781933-ed4bfd12-9bbf-45c4-9749-cc2bf5ce9e98.png)

I've tried to read about `break-after` and `break-before` properties, but still have no idea why it behaves this way

`break-before` was added by @calculuschild in #1184

**Comment by Gazook89** [comment] 2022-09-25 02:15
I think this is resolved at some point-- the property is now `break-after` rather than `-before`.  And I can't reproduce this.  Possibly it was the `columnWrapper` that did it?  I don't see it in the DOM in the screenshot above.

I'm going to close this-- please reopen if i'm mistaken.

**Closed by Gazook89** 2022-09-25 02:15 UTC
Labels: bug, ✅ Added to V3, ⚠️ Broken in V3
