### ISSUE TITLE
Curly syntax not working with values that have spaces.

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1495] opened 2021-08-01 01:05 UTC
In v3, this doesn't work:

`{{pen,#author,color:orange,font-family:"times new roman" Brian Sanderson}}`.  Nor this:
```
{{pen,#author,color:orange,font-family:"times new roman"
Brian Sanderson
}}
```
Not sure if #1485 removed the ability to use quotes at all?

**Comment by ericscheid** [comment] 2021-08-01 01:13
Well, this works: `{{pen,#author,color:orange,font-family:"courier" Brian Sanderson}}`

So, the problem is with the spaces inside the quotes.

**Comment by Gazook89** [comment] 2021-08-01 01:18
actually, i don't think it's an issue with further playing with it.  I first thought it was problem because I wanted to do "Comic Sans"  (i know i know...i was just testing something), which didn't work.  Then, I tried Times New Roman....i THOUGHT that didn't work, but I think now it was working but I misinterpreted it as going to a "base font" and *not* working.

I've since tried "Courier New" and "Brush Script MT" and found those to obviously work fine.  So maybe on my macbook Comic Sans just isn't...installed?  Seems odd to me, but I'm happy to close this unless someone can actually reproduce it.

**Comment by calculuschild** [comment] 2021-08-01 01:19
I'll check this out. Good grief. Lots of trickiness to these Marked.js extensions :P

**Comment by Gazook89** [comment] 2021-08-01 01:24
actually....it's weird.....so yeah, I did border earlier which is what made think it WAS working, and try some other font names.  Was ready to move on, but now look at this:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/58999374/127756192-bab26b5b-a4dc-42f8-ac4b-42f18f3bbad4.png">

It is accepting the font name "brush script mt"  AND the border " 2px solid", and applying that styling....BUT it is still also showing the text starting at `script mt....`

So it's both working, and not working?

**Comment by ericscheid** [comment] 2021-08-01 01:34
Confirming seeing the same wrong-match for content.

![image](https://user-images.githubusercontent.com/2605467/127756377-404cecc3-4d4b-4cc6-8550-6790898bd94b.png)

**Comment by calculuschild** [comment] 2021-08-01 02:44
Found the error. Fixing now.

**Comment by calculuschild** [comment] 2021-08-01 04:21
Should be fixed by https://github.com/naturalcrit/homebrewery/commit/4d087f4aa929fc2d1ee5da5103dbb3c6363e7421.

**Closed by calculuschild** 2021-08-01 04:21 UTC
Labels: bug, bug-regression
