### ISSUE TITLE
Problem Printing to PDF via Chrome

### ISSUE THREAD

**Issue by scrapheadx12** [naturalcrit/homebrewery#324] opened 2017-02-03 04:40 UTC
Weapons Table at the end is having problems while trying to print to PDF

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

### Lionshield Coster

<div class='descriptive'>
Hanging above the front door of this modest trading post is a sign shaped like a wooden shield with a blue lion painted on it.
</div>

This building is owned by the Lionshields, a merchant company based in the city of Yartar, over a hundred miles to the east.

The master of the Phandalin post is a sharp-tongued human woman of thirty-five named Linene Graywind. In a back room, Linene keeps a supply of armor and weapons, all of which are for sale to interested buyers. Linene has a few scruples, however, and won't sell weapons to anyone she thinks might be a threat to the town.

```
```

##### Armor
|Name|Cost|Armor Class (AC)|Weight|
|:----|:---:|:---:|:---:|
|*Light Armor*|||||
|Leather|10 gp|11|10 lb.
|Studded Leather|45 gp|12|13 lb.|
|*Medium Armor*||||
|Hide|10 gp|12|12 lb.|
|Chain shirt|50 gp|13|20 lb.|
|Scale mail|50 gp|14|45 lb.|
|Breast plate|400 gp|14|20 lb.|
|*Heavy Armor*||||
|Ring mail|30 gp|14|40 lb.|
|Chain mail|75 gp|16|55 lb.|
|Splint|200 gp|17|60 lb.|
|Shield|10 gp|+2|6 lb.|

<div class='wide'>
##### Weapons
|Name|Cost|Damage|Weight|Properties|
|:----|:----:|:---:|:---:|:---|
|*Simple Melee Weapons*|||||
|Dagger|1 sp|1d4 piercing|2 lb.|Finesse, light, thrown(range 20/60)|
|Handaxe|5 gp|1d6 slashing|10 lb.|Light, thrown (range 20/60)
|Javelin|5 sp|1d6 piercing|2 lb.|Thrown (range 30/120)
|Light hammer|2 gp|1d4 bludgeoning|2 lb.|Light, thrown (range 20/60)|
|Spear|1 gp|1d6 piercing|3 lb.|Thrown (range 20/60), versatile (1d8)
|*Simple Ranged Weapons*|||||
|Crossbow, light|25 gp|1d8 piercing|5 lb.| Ammunition (range 80/320), loading, two-handed
|Shortbow|25 gp|1d6 piercing|2 lb.|Ammunition (range 80/320), two-handed
|*Martial Melee Weapons*|||||
|Battleaxe|10 gp|1d8 slashing|4 lb.|Versatile (1d10)|
|Longsword|15 gp|1d8 slashing|3 lb.|Versatile (1d10)
|Maul|10 gp|2d6 bludgeoning|10 lb.|Heavy. two-handed|
|Shortsword|10 gp|1d6 piercing|2 lb.| Finesse, light|
|*Martial Ranged Weapons*|||||
|Crossbow, hand|75 gp|1d6 piercing|3 lb.|Ammunition (range 30/120), light, loading|
|Crossbow, heavy|50 gp|1d10 piercing|18 lb.|Ammunition (range 100/400), heavy, loading, two-handed|
|Longbow|50 gp|1d8 piercing|2 lb.|Ammunition (range 150/600), heavy, two handed|
</div>

<div class='pageNumber auto'></div>

</pre></code></details>

**Comment by CodeLabMaster** [comment] 2017-02-21 09:42
I'm also having a similar issue. I have four tables spread across four pages: a wide class table at the bottom of the page, a wide table at the bottom, a spell list at the bottom, and a wide table at the top. When attempting to print in Chrome, the print preview will have the first three tables all pushed a few hundred pixels down, pushing them off the page so they are mostly unviewable. The last table, the one at the top of the fourth page, is unaffected.

Also of note is that once I see this print preview, when I close this table and go back to the tab that the editor is in, the table on the first page has moved up by 20 or so pixels. To reset this, I have to make any change to the document (and I can undo this change right away) and it will move back to its normal position.

My share link is: http://homebrewery.naturalcrit.com/share/B1LDo6LFl

**Comment by calculuschild** [comment] 2021-01-08 21:39
duplicate of #144

**Closed by calculuschild** 2021-01-08 21:39 UTC
