### ISSUE TITLE
[request] command-line interface without need starting Chrome 

### ISSUE THREAD

**Issue by ttpro1995** [naturalcrit/homebrewery#1035] opened 2020-09-19 05:06 UTC
I suggest making an standalone app that does not depend on Chrome thing, Something similar to Latex. It can run from command line without starting any server. 

like this: 
```
homebrewery input.md output.pdf 
```

Because I can write stuff on file system (markdown file with text editor) and integrate with .git easily without need to copy and paste stuff from file to Chrome every time I build.

**Comment by RKuerten** [comment] 2020-10-25 16:01
There's this homebrewery app built on electron: https://github.com/noahlange/homebrewery-electron. It is basically what you're requesting.

**Comment by AlexeySachkov** [comment] 2021-01-14 06:22
Duplicate of #802?

**Comment by dbolack-ab** [comment] 2024-06-05 02:26
Going to close this as effectively duplicate of #802 as noted.

**Closed by dbolack-ab** 2024-06-05 02:26 UTC
