### ISSUE TITLE
Search/Replace tool in editor

### ISSUE THREAD

**Issue by lucastucious** [naturalcrit/homebrewery#1818] opened 2021-11-10 20:34 UTC
As mentioned in #1756 , a find/replace tool could be a great addition, especiall for large brews.

I think about something not too advanced, that can be triggered by CTRL+F or maybe a button, next to the "Properties" one.

<details>
<summary> I don't know if theses type of screenshot are allowed</summary>
here some suggestion from another similar editor 

![image](https://user-images.githubusercontent.com/28046122/141188794-69cab2cc-501e-4766-9a3d-03db70e66a82.png)

</details>

**Comment by G-Ambatte** [comment] 2021-11-10 20:45
This idea is already in motion - it was first recorded in #1201. @jeddai has been working on some other improvements to the editor and mentioned only a few hours ago that he had a working development build with these features implemented.

So while it still has to be put through the normal testing and release process, it is quite close to full implementation... Watch this space.

---

Closing as duplicate of #1201.

**Closed by G-Ambatte** 2021-11-10 20:45 UTC
Labels: duplicate

**Comment by jeddai** [comment] 2021-11-10 20:49
Just a note, my implementation as it currently stands is very basic and the exact implementation depicted in [CodeMirror's documentation for search and replace](https://codemirror.net/demo/search.html). I think getting it functioning is a great first step, then it can and probably should receive a UI overhaul similar to the screenshot you posted.
