### ISSUE TITLE
Class Table jumps to the top of the page?

### ISSUE THREAD

**Issue by Christian-Eichhorn** [naturalcrit/homebrewery#605] opened 2018-01-19 12:01 UTC
Hi,

I encountered an error I could reproduce, so I wanted to give you a heads up. You can find the code at the bottom. Basically, when you switch to A4 format and use a Class Table, it jumps to the top of the page.
To reproduce it open the code in a normal brew. Then type anything on the first page of the document, e.g. right under the headline "Hello World" **while looking at the class table**. It will jump almost to the top of the second page. When you type anything inside the class table it will jump back.

Happy hunting!

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>
# Hello World
Vae victis

## This is a Test

\page

<div class='classTable wide'>

##### The Fishmongerer
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | ─ | 3 | 11 | 2 | — | — | — | — | — | — | — | — |
| 2nd | +2 | Hermetic Geography | 3 | 2 | 2 | — | — | — | — | — | — | — | — |
| 3rd | +2 | Nuclear Illusionism | 3 | 3 | 4 | — | — | — | — | — | — | — | — |
| 4th | +2 | Ability Score Improvement, Pharmaceutical Gunslinger | 3 | 3 | 4 | 1 | — | — | — | — | — | — | — |
| 5th | +3 | Astrological Botany | 3 | 3 | 4 | 1 | — | — | — | — | — | — | — |
| 6th | +3 | Ability Score Improvement, Pharmaceutical Gunslinger | 3 | 3 | 4 | 1 | — | — | — | — | — | — | — |
| 7th | +3 | Mathematical Pharmacist | 4 | 3 | 4 | 2 | — | — | — | — | — | — | — |
| 8th | +3 | Ability Score Improvement, Gunpowder Torturer | 4 | 3 | 4 | 3 | 1 | — | — | — | — | — | — |
| 9th | +4 | Spiritual Biochemistry | 4 | 3 | 4 | 3 | 1 | — | — | — | — | — | — |
| 10th | +4 | Civil Alchemy | 5 | 3 | 4 | 3 | 2 | — | — | — | — | — | — |
| 11th | +4 | Genetic Banishing | 6 | 4 | 4 | 3 | 3 | 1 | — | — | — | — | — |
| 12th | +4 | Ability Score Improvement, Police Necromancer | 7 | 5 | 4 | 3 | 3 | 1 | — | — | — | — | — |
| 13th | +5 | Astrological Chemistry | 8 | 6 | 4 | 3 | 3 | 1 | — | — | — | — | — |
| 14th | +5 | Ability Score Improvement, Spell Analyst | 8 | 6 | 4 | 3 | 3 | 3 | — | — | — | — | — |
| 15th | +5 | ─ | 8 | 7 | 4 | 3 | 3 | 3 | 2 | — | — | — | — |
| 16th | +5 | Ability Score Improvement, Police Necromancer | 9 | 8 | 4 | 3 | 3 | 3 | 3 | — | — | — | — |
| 17th | +6 | Civil Alchemy | 9 | 9 | 4 | 3 | 3 | 3 | 3 | 1 | — | — | — |
| 18th | +6 | ─ | 9 | 10 | 4 | 3 | 3 | 3 | 3 | 2 | 1 | — | — |
| 19th | +6 | Ability Score Improvement, Sixgun Poisoner | 9 | 10 | 4 | 3 | 3 | 3 | 3 | 2 | 2 | — | — |
| 20th | +6 | Consecrated Biochemistry | 10 | 10 | 4 | 3 | 3 | 3 | 3 | 2 | 2 | 1 | 1 |
</div>

</pre></code></details>

**Comment by HeruAsatru** [comment] 2018-02-23 08:32
I noticed this too, but it apparently has no impact when "getting PDF". you just have to be aware of it when layouting the actual site where the table is on.

**Comment by Gazook89** [comment] 2021-01-04 18:12
This 2 year old issue can likely be closed.  The original code provided doesn't even match the current snippet for class tables, and after some tinkering I couldn't reproduce it.  Unless @HeruAsatru  or @Christian-Eichhorn are still seeing the same issue at this point, let's close this one out. @ericscheid @calculuschild

**Comment by calculuschild** [comment] 2021-01-04 21:14
I also cannot reproduce this. May have been related to #295, but this particular instance seems to have been fixed with updates to Chrome. Closing.

**Closed by calculuschild** 2021-01-04 21:14 UTC
