### ISSUE TITLE
Markings left behind on pages with monster statblocks

### ISSUE THREAD

**Issue by iastreb** [naturalcrit/homebrewery#806] opened 2018-11-18 19:30 UTC
Pages with monster statblocks on them sometimes reproduce lines or gray boxes on pdf version of brews.

E.g.
![screen shot 2018-11-18 at 2 27 15 pm](https://user-images.githubusercontent.com/43016125/48677117-253c2b00-eb3e-11e8-9540-3328a2634a6a.png)

or 

![screen shot 2018-11-18 at 2 28 59 pm](https://user-images.githubusercontent.com/43016125/48677133-616f8b80-eb3e-11e8-97d3-8b72eb473558.png)

Is there a patch for eliminating them?

**Comment by calculuschild** [comment] 2018-11-18 20:08
Which version of Chrome are you using?

**Comment by iastreb** [comment] 2018-11-18 20:30
Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by calculuschild** [comment] 2018-11-19 14:20
Hmmmmmm..... Looks like an issue with shadows being rendered? Can you provide a "share" link to a document that has this issue so we can take a look at it?

**Comment by iastreb** [comment] 2018-11-19 19:15
Issue occurs on pp. 259 - 268

http://homebrewery.naturalcrit.com/edit/rklSpwIczQ

**Comment by calculuschild** [comment] 2018-11-19 19:18
Thanks! Could you please replace this with your "share" link rather than
the "edit" link? That way somebody doesn't come along and mess up your
document. You can do this by clicking the "share" button on the top-right
and copying the URL from there.

**Comment by iastreb** [comment] 2018-11-19 19:20
http://homebrewery.naturalcrit.com/share/r1HawL9z7

**Comment by calculuschild** [comment] 2018-11-21 00:02
I'm unable to reproduce the issue. This is what your monster blocks looks like in the PDF on my end:

![image](https://user-images.githubusercontent.com/5878534/48810310-a0484180-ecf6-11e8-99fa-c108de09a8a9.png)

Have you noticed this on every monster block, or is it just occasionally? What happens if you have a smaller document with just a monster block and nothing else?

**Comment by iastreb** [comment] 2018-11-21 03:41
Strange. So you think it's a browser issue?

Not 100% sure, but it seems to happen if you make a mistake with the
statblock (so the bottom borders don't show correctly), and once you fix
it, you the lines get left behind (and then turn into grey blocks for some
reason).

It's not a big deal, but I thought it would be as easy to fix as the
borders on the class table or the descriptive text box..

**Comment by calculuschild** [comment] 2020-10-25 03:13
Sorry, this issue dropped off our radar somehow. Closing since this was likely an individual browser issue. 

If you are still experiencing this issue, feel free to reopen and provide information, @iastreb

**Closed by calculuschild** 2020-10-25 03:13 UTC
