### ISSUE TITLE
`undefined` css code blocks in /source

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1846] opened 2021-11-20 07:47 UTC
If a brew doesn't have any css added via the editor panel, the brew when viewed via `/source` will have a css code-block prepended that looks like this:

````
```css
undefined
```
````

That's a bug, easy to fix.

Also appears in the `/download` resource.

**Comment by Gazook89** [comment] 2021-11-20 16:34
If no document styles are specified, should there be no style block at all?  Or should it show as:

```
```css
No document-wide styles defined  (or alternate message)
```\
```

Unrelated, but how did you get code fence to show in github (how to escape the grave accents)?

**Comment by calculuschild** [comment] 2021-11-20 17:01
I think it should be blank or not there at all. Filling it with other text adds an extra step to determine if it's actually empty.

Markdown can also display code by indenting the whole block four spaces which let's you escape the backticks.

**Comment by Gazook89** [comment] 2021-11-20 17:17
Agreed, I couldn't think of a good message to go in that spot anyway--- just because it's not entered int he Style editor doesn't mean there isn't "document wide styles" in the main content via style tags.

Okay, i may pick this up this weekend and try my hand (however, if anyone beats me to it I won't be upset :smile: )

**Comment by ericscheid** [comment] 2021-11-21 08:40
![image](https://user-images.githubusercontent.com/2605467/142755478-8e366a7b-d82a-454f-851d-8c6ea229c32b.png)

**Comment by calculuschild** [comment] 2021-11-21 19:04
Reading this issue again I realize I misunderstood ehat part of the code this was referring to. `undefined` here is not a bug, but intentional because we need to differentiate between two states:

1) The user has never touched the Style tab for this document, in which case we need to display some default filler text. If this is the case, we put `undefined`.

2) The user *has* touched the Style tab and intentionally deleted all of the sample text to have the Style tab blank. If this is the case, we just have the CSS block blank. We don't want default text coming back every time the user deletes the contents of that tab.

I can see how this would be confusing though, and so perhaps the better solution is to entirely remove the block to represent `undefined`. Then, on loading, it is easy to see whether any style data exists and whether to inject the default text.

**Comment by calculuschild** [comment] 2021-11-21 19:20
Actually, I take that back. You're right, we don't deliberately inject the string "undefined" anywhere so proper behavior should be to not have the CSS block at all. If the the style tab was never touched.

**Comment by Gazook89** [comment] 2021-11-21 19:25
So #1850 does this:
1. If style tab isn't touched from "new", the example styling doesn't appear, and no code fence block.
2. If it's changed, the change appears
3. If it's changed, but entirely deleted, it shows the code fence block but is empty:

````
```css

```
````

**Comment by calculuschild** [comment] 2021-11-24 05:51
@ericscheid Can you provide specific steps to reproduce this? The only way I can think to get this behavior is on older documents made when we were first getting the Style tab working (in which case there's not anything we can do). New documents do not have this behavior that I can see.

**Comment by ericscheid** [comment] 2021-11-24 05:59
@calculuschild testing just now and I concur. It must have been an old brew I was looking at. What we can do is make sure we don't consume the string "`undefined`" from an old brew and stick that into the style editor.

Ah, found these two in my downloads folder:

https://homebrewery.naturalcrit.com/share/HJ-xEkR-77
https://homebrewery.naturalcrit.com/share/1Xy5P5f_d4aYQ8mSSTATBQtKuOLqI8Qs7N7hF0h2ml8Gf

**Comment by calculuschild** [comment] 2023-05-28 01:39
Closing, since I think we are in agreement that since this is only a leftover from certain old brews, but doesn't cause any noticeable issue other than an oddity in the source results.

**Closed by calculuschild** 2023-05-28 01:39 UTC
Labels: bug, solution found, tweak, P2 - minor feature or not urgent
