### ISSUE TITLE
Table headers duplicated when rendering PDF

### ISSUE THREAD

**Issue by rgiannico** [naturalcrit/homebrewery#318] opened 2017-01-31 15:07 UTC
What happens: printing the final PDF, the table header seems to be repeated over all the table randomly (see attached pic).

When it happens: My code renders fine on the "edit" mode, fine on the "print" mode (clicking on 'get PDF') but the issue appears on the printing preview windows to actually print or save the PDF. If I save the PDF the issue remains. 

Note: I'm using Chrome on a Mac. It seems happening if you have a two-column section, then a `<div class='wide'>` , followed by a table in a two-column section (see brew code below). Do you see the same problem? Is there a way to fix it?

<img width="453" alt="schermata 2017-01-31 alle 15 43 49" src="https://cloud.githubusercontent.com/assets/2571713/22470274/07071984-e7cf-11e6-97e5-98c791e01eb9.png">

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>
```

<div class='wide' style='text-align: center;'>
# Character Name
</div>

 
**Concept:** Character Concept

Some text here for the description of the character to be. Some text here for the description of the character to be
 


<div class='wide' style='text-align: center;'>
### ~~ :: ~~ :: ~~ :: ~~
### Charisma:  +2  ;  Parry:  5  ;  Pace:  6”  ;  Robustness:  5
</div>

##### Cookie Tastiness
| Tastiness | Cookie Type |
|:----:|:-------------|
| -5  | Raisin |
| 8th  | Chocolate Chip |
| 11th | 2 or lower |
| 14th | 3 or lower |
| 17th | 4 or lower |
| 8th  | Chocolate Chip |
| 11th | 2 or lower |
| 14th | 3 or lower |
| 17th | 4 or lower |
```

</pre></code></details>

**Comment by stolksdorf** [comment] 2017-01-31 15:55
Weird bug. Good isolation of the cause though.

**Comment by rgiannico** [comment] 2017-01-31 16:07
Thank you, 
I can add some more info if you like (maybe it helps to find the cause): 
It seems like the biggest is the first two-column section , the biggest is the distances between the doubled header in the table. Maybe the distance between the fake header depends on the height of the first two-column section (and it is weird) 

<img width="420" alt="schermata 2017-01-31 alle 17 03 42" src="https://cloud.githubusercontent.com/assets/2571713/22472917/5207c5b6-e7d7-11e6-933e-8b1a072569af.png">

**Comment by calculuschild** [comment] 2017-02-03 13:04
Solution:

Add this bit of CSS to the code:

<pre><code>
.phb table thead { display: table-row-group;}
</code></pre>

From w3 schools: _"...when printing a large table that spans multiple pages, the [thead and tfoot] elements can enable the table header and footer to be printed at the top and bottom of each page."_  It looks like the column-span: all is somehow causing subsequent tables to confuse chrome's PDF printer about where the top of a new page is. display: table-row-group will force it to print just like any other table row, only once per page.

**Comment by rgiannico** [comment] 2017-02-03 13:16
WOW! Thanks a lot @calculuschild !
I tested it and it fixes the bug perfectly! Amazing! 
@calculuschild Don't you think this line of code should be added by default to avoid similar issues? Or it's better not to because it could cause some other issues?

**Comment by calculuschild** [comment] 2017-02-03 13:59
I would recommend it be added to the codebase, yeah. There might need to be some testing to make sure it didn't mess anything else up, but I'm pretty sure it wouldn't.

My real question though is why the _column-span: all_ is causing the PDF printer to get confused in the first place. Might be a bug in Chrome's PDF rendering backend (and they do have lots of bugs), or something else in the Homebrewery making it weird. I did a test on my local machine with some unstyled html, but the printing bug doesn't show up until I apply the Homebrewery css styles to it.  It didn't seem to be anything within the _thead_ sections that was causing the problem (deleting them changed how the headers looked but they still printed all over the table).

**Comment by Jamezila** [comment] 2017-05-25 23:53
Hey,

I've got the same problem, but I'm kind of weak on css/markdown/html, don't know how to implement the css change! Where do I throw that in?

Thanks!

**Comment by Jamezila** [comment] 2017-05-25 23:54
I have noticed that it seems like the dupe headers show at a fixed y value, and if the table starts below that value, they don't show. Also, it only happens waaaaay later in the doc, like 30+ pages in. Might be why this is more of an edge case?

**Comment by rgiannico** [comment] 2017-05-26 07:49
@Jamezila 
You can just add that line of code inside the "style" tag at the beginning of your document. 
Here there is an example where I define the style of my pages as an A4 (210x296.8cm) and then I apply this trick to all the table objects from my document:
 

```
 <style>
    .phb{
      width : 210mm;
      height : 296.8mm;
    }
   .phb table thead { display: table-row-group;}
 </style>
```

**Comment by calculuschild** [comment] 2019-10-02 03:31
This was fixed a long while ago. Closing.

**Closed by calculuschild** 2019-10-02 03:31 UTC
Labels: complicated, ready to add
