### ISSUE TITLE
Usernames ending in whitespace do not load brews from userpage

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2420] opened 2022-10-06 18:12 UTC
### What happened?

A user somehow ended up with a username with an empty space at the end: "username " . This meant all his brews were given an author with a blank space as well. However, loading the user page truncated the space, so it was showing "username's page" as a different user. Not sure at what point along the code the break is, but we should:

- [ ] Ensure the full username is being passed to the brew retrieval for the user page 
- [ ] Double-check this doesn't also apply to usernames with spaces elsewhere (beginning or in the middle)
- [ ] Prevent usernames being created that end/start with spaces? (NaturalCrit) Maybe not as necessary.

Was able to resolve this by fixing their username in the database, and then all the brews loaded properly, even though they have a space in their author list.

Putting at low priority since this is the only report I've heard of this and I suspect it's rare.

**Comment by G-Ambatte** [comment] 2022-10-08 01:45
I think this is actually browser jank. Uh, I mean, feature.

I have a user in my local DB `"test"` who has multiple test brews. Logging in as `"test "` and navigating to the User Page `"/user/test "` (via the Account nav bar item) results in "test"'s user page `"user/test"`, with only that user's published brews visible - not the logged in user, `"test "`.
Attempting to manually navigate to `"user/test "` also results in redirection to `"/user/test"`.

Decoding the JWT token showed that the trailing space was preserved in the cookie:
![image](https://user-images.githubusercontent.com/19826659/194681082-c412e396-7b7b-4c27-b19e-adfae7b6bcfe.png)

A fix for this was seems to be to change the navbar item like so:
![image](https://user-images.githubusercontent.com/19826659/194681066-94037bf5-2879-4b9f-994a-17916474cdc6.png)

This results in the account page being linked to `"/user/test%20"` which has all of the brews associated with the logged in user `"test "`.

---

Repeating the manual test for `"test user"` resulted in the space being automatically replaced, resulting in `"/user/test user"` being directed to `"/user/test%20user"`. Similarly, `"/user/ test user"` was directed to `"/user/%20test%20user"`.

---

So it appears that the issue is literally ONLY trailing spaces, and the fix is to change the Account nav bar item. I will submit a PR shortly - despite the difficulty in determining what is/was happening, it's actually a very simple fix.

**Closed** 2022-10-18 18:11 UTC
Labels: P2 - minor feature or not urgent
