### ISSUE TITLE
Equal (=) Issues

### ISSUE THREAD

**Issue by Swifterduster55** [naturalcrit/homebrewery#292] opened 2017-01-15 03:44 UTC
There are a few instances in which the equal sign (=) sign shows up as an elongated hyphen (-). I'm unsure what causes this or even if its a bug with my computer. Keep up the great work, I absolutely love Homebrewery!

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

### Barbarian: Path of The Twister

A burly human, tattooed with images of clouds, rain, and wind, stands stoically against a storm, watching a cyclone tear apart his hut before slowly walking towards it. 
A woman, clad in furs, wields two handaxes while enemies surround her completely. She smiles before unleashing a spinning attack, paving a path through her enemies.

The most hardy Saffiric live in the wilds, away from the beautiful palaces and cities. These Saffiric know how to live off the land and withstand any storm. In fact they idolize the power of the storm, adopting fighting styles of the very thing that destroys their homes: the Tornado.

#### Aerodynamic

Beginning at first level, if you are not wearing armor, your AC = 10 + Dex modifier.

#### Furious Winds

It’s just the barbarian’s rage with a fun name.

#### Spin Attack

At 3rd level you can control the Furious Winds for a small burst. As an attack action, you can make a Spin Attack, hitting every creature within 5 ft of you with disadvantage. Spin attacks double the weapon damage. 

#### Resilient

At 6th level you have mastered the force of the tornado. You gain advantage on any saving throw against being pushed back. You are also resistant to force damage. When force damage is done, you get a reaction to do ½ the damage you took back to the attacker.

#### Boomerang

At 10th Level, you have gained the ability to use small whirlwinds to throw and retrieve your weapons. You may make a ranged weapon attack using any weapon and concentrate up to a minute, hitting anything within a 60 ft radius. You can bring it back to yourself with a bonus action. This does normal weapon damage in addition to 1d6 force damage. This increases as you level. 

#### Improved Furious Winds

At 14th level, you gain the ability to actually create a cyclone. Using your Furious Winds, you can begin a small tornado that will wreak havoc on anyone in it’s path. Furious Winds must be used for 3 turns and a bonus action can be used to release the energy, ending your rage and creating a tornado. The tornado will have a random pattern, unless you concentrate and control it. The tornado will do 3d6 force damage, or 3d8 if there is a lot of debris around.

<img src='' 
  style='position:absolute; top:50px; right:30px; width:280px' />

<div class='pageNumber auto'></div>

\page
</pre></code></details>

**Comment by stolksdorf** [comment] 2017-01-15 04:36
I can't seem to reproduce it. Can you provide more examples of code with screen shots?

On a unrelated note, is there any reason why you didn't follow the issue submission format? I've tried to tweak what is says many times but many user's still don't follow it. Any way I can improve it?

**Comment by calculuschild** [comment] 2021-01-08 21:51
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Swifterduster55

**Closed by calculuschild** 2021-01-08 21:51 UTC
Labels: blocked
