### ISSUE TITLE
{Issue} page numbering issue when exporting to PDF

### ISSUE THREAD

**Issue by Valsavus** [naturalcrit/homebrewery#1011] opened 2020-08-02 01:29 UTC
When exporting to PDF my page numbers change after page 84.  The following page jumps to 89,

https://homebrewery.naturalcrit.com/share/QGJcfl_m4

You can see in the above shared file that it has page 84,85...  Only when exported to PDF does the page number change.

I am using <div class='pageNumber auto'></div>

I can manually drop in the page numbers and that only caused the following page to increment by 5 pages.  Any ideas on why exporting to PDF I have this issue>

**Comment by calculuschild** [comment] 2020-08-02 18:06
I see that the text on Chapter III : backgrounds is overflowing into a third column off the edge of the page. I don't know if that is related, if the page count is getting off because the its starting to count overflowed text as extra pages, but it might be.

**Comment by Valsavus** [comment] 2020-08-03 16:01
I checked the background section and couldn’t find any that bled over to a second page.  I went back through the previous pages and couldn’t find any either

**Comment by ericscheid** [comment] 2020-11-12 07:19
Looking at page 84 "Chapter III: Backgrounds" I too see the overflow into 3rd column in the browser preview, but when printed to PDF that overflow doesn't happen. I noticed a couple of other places where there was small overflows too. 

I also noticed that it looks like you are using the column breaker six-backticks code in column-one .. this is because on pages where column one fills almost all the first column the first heading of column two is visibly bumped down by about one blank paragraph worth. Which tracks with a known behaviour (the column breaker gets rendered as `<p><code></code></p>` and all `<p>` have `bottom-padding: 0.85em;` .. so, the `<p/>` doesn't fit at the bottom of column, and bumps to column 2, and the padding-bottom takes up space). This then bumps all the content downwards a line, which on long columns causes the last paragraph to auto-overflow into column 3.

Unless ... there are slightly different font-metrics in play, and the first column is just short of being full such that the blank one-line paragraph containing the element with `break-after: column` fits just fine, doesn't flow to column-2, doesn't impose padding-bottom above the content of column-2, which leaves just enough space for column-2 to fully fit without overflowing.

By the looks of it, what actually gets sent to the actual PDF has that slightly differnt font-metric, which is why the column overflow isn't apparent in the actual PDF. (I'm saying "actual PDF" to differentiate from the browser html view achieved by clicking the Get PDF button and living on the url /print/:id)

Now, I might also be viewing your shared brew on a different OS than you, and thus fonts might be slightly teensy slightly different ... which would explain why I'm seeing a column overflow and you are not.

----

**The page numbers, in the editor preview, the shared render, and in the PDF are all fine though — not seeing this particular bug.**

Closing due to no-repro. OP can re-open if confirmed still an issue.

**Closed by ericscheid** 2020-11-12 07:19 UTC
