### ISSUE TITLE
V3: Preview changes depending on browser zoom level

### ISSUE THREAD

**Issue by hakr14** [naturalcrit/homebrewery#1691] opened 2021-09-16 02:26 UTC
Where an automatic column break occurs appears to be dependent on the browser zoom level.

As an additional point, the provided example brew below comfortably fits on a single page in the legacy renderer but appears not to at all in V3.

**Example brew code to reproduce** : <details><summary>Click to expand</summary>

<pre><code>
{{pageNumber 1}}
{{footnote INTRODUCTION}}
# Introduction
To most, reality as we understand it follows<br>certain rules. These rules, indeed, define reality. Anything that exists must follow these rules, and anything that follows these rules could exist. However, there are some unfortunate enough to experience something that operates beyond these rules, beyond our reality. We call these objects &ldquo;anomalous,&rdquo; and they are far more wonderful and extraordinary than anything the non-anomalous world could offer. However, they are also significantly more dangerous, and mere knowledge of their existence could upend public life as we currently know it. For this reason, anomalous objects should be kept secure, contained, and protected. This is the purpose of the Foundation.
### The Foundation
The Foundation is an organization unaffiliated with any government or guild, comlpetely unbound and independent, with far reaching power. Indeed, if anything, the Foundation affects world governments. However, we are far from the shadowy all-powerful collective that paranoid theorists would have you believe. While the Foundation does try to stay out of the public consciousness as much as possible, this is done only to ensure success in our mission statement.

The Foundation's mission statement is:
1. **Secure**: Retrive the object and ensure public ignorance.
2. **Contain**: Contain the object and its anomalous effects.
3. **Protect**: Protect the object and protect the public.

### Defining the Undefinable
Defining &ldquo;anomalous&rdquo; rigorously is always difficult, but the intricacies of magic make the line between the known and the unknowable even blurrier. The Foundation has compiled a complete definition of reality as currently understood, and simply defines an anomaly as anything which, under that definintion, should not be able to exist.

Of course, there are many things which at first appear to be anomalous, but can be explained through non-anomalous means, such as intricate mechanical or magical components. Sometimes items that are classified by the Foundation as anomalous but are later found to be explainable, be it through further research into the item or expanding scienticfic understanding. When this happens, the item's anomalous classification is revoked.

There are some objects which cannot be explained under the laws of reality, but cannot be classified under the Foundation. This happens when an item enters the public conciousness before the Foundation&rsquo;s involvement, and the confusion resulting from its sudden seeming disappearance would be infeasible for the Foundation to resolve. Additionally, in extremely rare cases, the Foundation classifies an object, but its continued classification becomes infeasible, improbable, or immoral.

Explained, unclassified, and declassified objects will not be included in the Guide.
### The Guide
While the Founation typically never uses anomalies<sup>1</sup>, there are certain anomalous objects which have proven themselves to be both particularly useful and extremely safe. This book is one such object. The Guide hosts two anomalous effects which make it ideal for use by the Foundation.

First, any anomalous effect relating to the storage, reading, or understanding of information is nullified when that information is stored within these pages. However, it is important to note that this does NOT mean that the danger is not present at all, as transferring the information to another source without the same anomaly (such as writing it on ordinary paper, or speaking it aloud) will allow the original anomaly to take effect. For this reason, it is important to take extreme caution with regards to all infromation within this guide. Certain particularly dangerous information will have additional warnings associated with it, but the reader should not waive caution if those warnings are not present.

Second, information within this book which an individual is not permitted, authorized, or prepared to access is not percievable to that individual. The existence of the information is also itself inpercievable, and even the page numbers are corrected if necessary, meaning that it is impossible to know how much of the true content of the Guide any one reader is allowed to see.

These anomalies make the Guide a perfect storage medium for dangerous classified information, which is exactly why the Foundation put it to use. However, it is important that the reader keep in mind that these anomalies are present, so as not to become too cavalier in the sharing of the content of these pages, which, as mentioned, could itself be a danger. It is also important to remember that any one reader is almost certainly not able to see all the content within the Guide, meaning that no one person can have complete knowledge of the anomalous. Finally, as useful as the Guide is, it is still an anomalous object, and must be handled with great care.
> ##### Note for DMs
> The Foundation deals with anomalies far outside the normal bounds of reality. The items and creatures in this book are not guaranteed to be balanced in the traditional sense. Many creatures here can outright end a campaign. Use caution, and be sure your players are prepared for a unique experience.

</code></pre></details>

**Comment by calculuschild** [comment] 2021-09-16 04:11
Thanks for the feedback!

Unfortunately, just by the nature of browser-based apps, there are multiple small things that can cause the display to grow or shrink slightly. See https://github.com/naturalcrit/homebrewery/issues/625 .  Fortunately, you can always insert a manual column break using `\column` and this will *usually* keep things in place a bit better even when zooming in and out, unless your columns are within 1 or 2 pixels of being totally full.

As for the example you provided, yes, the font sizes in V3 as well as the margins have been increased slightly to better match the actual PHB.  If you need to squeeze some more things on a page, you can always manually edit the CSS for your document using the style tab on your document. Try something like:

```
.page {
  margin-bottom: 1cm;
}
```

**Comment by calculuschild** [comment] 2021-09-22 20:14
Closing as a duplicate of #625

**Closed by calculuschild** 2021-09-22 20:14 UTC
Labels: duplicate
