### ISSUE TITLE
[Issue] Centering a title makes the rest of the text invisible

### ISSUE THREAD

**Issue by Singador** [naturalcrit/homebrewery#1013] opened 2020-08-03 17:04 UTC
Hello fellow brewers!

I've been hit by a bit of a conundrum. Last I opened my brews, all center-aligned titles worked just fine but recently, all text below a centered title is made invisible as can be seen [here](https://homebrewery.naturalcrit.com/share/PE4pvHl-).

For further illustration, on a page containing 

<details><summary>Click to expand</summary><code><pre>

> <div style="text-align: center"> Chapter 3: Oaths And Shadows
</div>

> Having broken the smuggling ring below the House on the Cliff, the players have set foot on the path to making a name for themselves in the Greyreach. Now owning a home of their own in Camarthen, the locally rooted factions will vye for their allegiance as the hidden powers of the Greyreach's schemes start to unfold. 

</pre></code></details>

the entire second paragraph is invisible.

What do you brewers most wise recommend?

**Comment by calculuschild** [comment] 2020-08-04 01:44
It seems like it's working fine on my end. Is this what I should be seeing? Are you using Chrome?

![image](https://user-images.githubusercontent.com/5878534/89243659-76ba7100-d5d2-11ea-9e14-0ff189572c47.png)

**Comment by Singador** [comment] 2020-08-04 18:55
> It seems like it's working fine on my end. Is this what I should be seeing? Are you using Chrome?
> 
> ![image](https://user-images.githubusercontent.com/5878534/89243659-76ba7100-d5d2-11ea-9e14-0ff189572c47.png)

Hello!

I'd tinkered with the code, but results are still messy, the title is shifted downwards and cannot be moved back to its original position. I have restored the brew to how it was originally, if you are alright with checking again.

**Comment by ericscheid** [comment] 2020-11-11 16:23
Checked just now, and still not seeing the issue occur.

**Comment by ericscheid** [comment] 2021-07-26 13:06
The original brew is no more.

No resolution, no further information, unable to reproduce.

Closing.

**Closed by ericscheid** 2021-07-26 13:06 UTC
Labels: bug
