### ISSUE TITLE
Having problems with saving my Homebrewery file

### ISSUE THREAD

**Issue by Leock06** [naturalcrit/homebrewery#1782] opened 2021-10-30 02:17 UTC
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71842:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72151:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

So, I've been trying to save my new file and even after reloading the website many times it just doesn't save :( how can I fix that?

**Comment by Gazook89** [comment] 2021-10-30 03:09
Check out discussion #1580 for a solution. If those steps don't work, swing back here.

**Comment by 5e-Cleric** [comment] 2021-11-03 15:03
Duplicate of #1734

**Comment by Gazook89** [comment] 2021-11-20 16:58
Closing this issue due to no activity, but if the steps in #1580 didn't help resolve the saving issue let us know here and we can reopen this.

**Closed by Gazook89** 2021-11-20 16:58 UTC
