### ISSUE TITLE
Forgot password, no link

### ISSUE THREAD

**Issue by Jibinhok** [naturalcrit/homebrewery#698] opened 2018-05-20 21:17 UTC
Hi, I refreshed my saved passwords in chrome and forgot the password for my account. Username is Jibinhok. I don't have an edit or share link to my brew, is there anything you can do to help?

**Comment by wmealing** [comment] 2018-06-15 16:34
Oddly I'm in the same situation.  @stolksdorf  mentioned that they were mid planning to use passport.js which will allow logins using third party auth providers.    I have looked around and can't see a 'forgot password' link.  Maybe if we wrote it as a pull request you/I might be able to get your account back ;)

**Comment by Gazook89** [comment] 2021-09-29 00:49
duplicate of #776 but that Issue thread has a little more detail, so closing this one.

**Closed by Gazook89** 2021-09-29 00:49 UTC
