### ISSUE TITLE
ToC not fitting on page

### ISSUE THREAD

**Issue by jbdryden** [naturalcrit/homebrewery#367] opened 2017-03-21 22:10 UTC
I have been having trouble getting my Table of Contents to fit on one page. Each new chapter (using the single-hashtag title) creates a new column on the ToC with no way to alter this and no way to get it to go on multiple pages.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2021-01-09 00:09
Closing since the problem isn't clear, but we have made many related improvements since this was posted so the issue may be solved.

If you are still experiencing this issue, feel free to reopen and provide information, @jbdryden

**Closed by calculuschild** 2021-01-09 00:09 UTC
