### ISSUE TITLE
Can't change the edition metadata tags

### ISSUE THREAD

**Issue by bretlinne** [naturalcrit/homebrewery#558] opened 2017-11-22 07:33 UTC
I made a [magic item](http://homebrewery.naturalcrit.com/share/ry-Mnu9flM) and published it with the Pathfinder, 3.5 and 5th ed tags.  I was quickly informed that I don't know anything about 5th ed and that my item doesn't fit.  However, I can't edit the metadata tags.  When I go to 'uncheck' the 5th ed. tag, and save it, the next time I look at the file, that metadata tag has reset to 'checked'.

I'm not sure how to correct this without trashing the homebrew, re-writing it in a clean file and then publishing it again with the correct tags.

**Comment by ericscheid** [comment] 2020-11-12 01:29
Bug confirmed. By "next time I look at the file" the OP means after a reload (e.g. close window, click link to edit brew). This is affecting each of the version tags. Unchecking any does not save.

Good news: the version tags are intended for an eventual public directory of published brews .. which doesn't exist yet, so we've got time to fix this.

**Comment by ericscheid** [comment] 2021-08-15 00:11
More detail on the bug in issue #1221.

**Comment by calculuschild** [comment] 2021-08-31 01:08
Closing this since the main discussion and related solution has moved to #1221 .

**Closed by calculuschild** 2021-08-31 01:08 UTC
Labels: bug
