### ISSUE TITLE
L's and Borders Messed Up in PDF

### ISSUE THREAD

**Issue by dmmagic** [naturalcrit/homebrewery#297] opened 2017-01-20 06:06 UTC
When converted to PDF, lowercase L's are bolded and the borders on descriptive text boxes are coming out weird.

**Share Link** : http://homebrewery.naturalcrit.com/edit/HkMuP_m1ve

![image1](https://cloud.githubusercontent.com/assets/15933118/22138038/80be9030-de93-11e6-88de-b1259c9d9ccf.png)

**Comment by stolksdorf** [comment] 2017-01-20 14:45
what a weird bug. Thanks for reporting it.

**Comment by wrdclark** [comment] 2017-01-24 14:27
The lower case L issue has been around in PDFs for years (Google results going back to 2008)... Not sure if this is something you'll be able to solve locally.

**Comment by stolksdorf** [comment] 2017-01-24 16:29
Thanks for the info @wrdclark . I haven't seen that bug before. I wonder if it's related to the border-image issue as well.

**Comment by calculuschild** [comment] 2021-01-09 00:03
Closing since Google has made many related improvements to Chrome since this was posted, and we can no longer reproduce the issue.

If you are still experiencing this issue, feel free to reopen and provide information, @dmmagic

**Closed by calculuschild** 2021-01-09 00:03 UTC
Labels: complicated
